#!/bin/bash
echo "Este es un archivo de prueba. Buscando la palabra secreta. " > mi_archivo.txt
echo "Contenido del archivo mi_archivo.txt:"
cat mi_archivo.txt
echo "Tipo de archivo de mi_archivo.txt:"
file mi_archivo.txt
echo "Buscando la palabra 'secreta' en mi_archivo.txt:"
grep -i "secreta" mi_archivo.txt
base64 mi_archivo.txt > mi_archivo_base64.txt
echo "Contenido del archivo mi_archivo_base64.txt:"
cat mi_archivo_base64.txt
echo "Listando los archivos en el directorio:"
ls -l
echo "Uso de disco del archivo mi_archivo.txt:"
du -h mi_archivo.txt
sort mi_archivo.txt > mi_archivo_sorted.txt
echo "Contenido del archivo mi_archivo_sorted.txt:"
cat mi_archivo_sorted.txt
cat mi_archivo.txt | tr '[:lower:]' '[:upper:]' > mi_archivo_transformado.txt
echo "Contenido del archivo mi_archivo_transformado.txt:"
cat mi_archivo_transformado.txt
echo "Script completado."
